version: '3'

services:
  postgresdb:
    image: postgres:13.3
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: fermenter_db
