service: fermenter-api

provider:
  name: aws
  runtime: nodejs14.x
  region: ap-southeast-1
  deploymentBucket:
    name: fermenter-api-production

plugins:
  - serverless-deployment-bucket
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    includeModules: true
    packager: 'yarn'

functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
