service: fermenter-api
useDotenv: true
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  region: ${env:REGION}
  deploymentBucket:
    name: fermenter-api-${opt:stage}

  environment:
    REGION: ${env:REGION}
    TOKEN_SECRET: ${env:TOKEN_SECRET}
    TOKEN_EXPIRY: ${env:TOKEN_EXPIRY}
    POSTGRESDB_USERNAME: ${env:POSTGRESDB_USERNAME}
    POSTGRESDB_PASSWORD: ${env:POSTGRESDB_PASSWORD}
    POSTGRESDB_HOST: ${env:POSTGRESDB_HOST}
    POSTGRESDB_PORT: ${env:POSTGRESDB_PORT}
    POSTGRESDB_DB_DATABASE_NAME: ${env:POSTGRESDB_DB_DATABASE_NAME}

plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-vpc-discovery

custom:
  webpack:
    includeModules: true
    packager: 'yarn'
  vpcDiscovery:
    vpcName: fermenter-${opt:stage}-vpc
    subnets:
      - tagKey: Name
        tagValues:
          - fermenter-${opt:stage}-vpc-private-ap-southeast-1a
          - fermenter-${opt:stage}-vpc-private-ap-southeast-1b
          - fermenter-${opt:stage}-vpc-private-ap-southeast-1c

functions:
  graphql:
    handler: src/apollo-server.graphqlHandler
    events:
      - http:
          path: graphql
          method: post
          cors: true
      - http:
          path: graphql
          method: get
          cors: true
